version: "3"

services:
  azure-sql-edge:
    image: mcr.microsoft.com/azure-sql-edge
    container_name: azure-sql-edge
    restart: unless-stopped
    environment:
      ACCEPT_EULA: ${ACCEPT_EULA}
      MSSQL_PID: ${MSSQL_PID}
      MSSQL_SA_PASSWORD: ${MSSQL_SA_PASSWORD}
    ports:
      - "1433:1433"
    volumes:
      - mssql-data:/var/opt/mssql

volumes:
  mssql-data:
    driver: local
    driver_opts:
      type: "none"
      o: "bind"
      device: "${PORTAINER_FOLDER}/mssql/data"
