version: "3"

services:
  minio:
    image: minio/minio
    container_name: minio
    restart: unless-stopped
    volumes:
      - minio-data:/data
    ports:
      - "8000:9000"
      - "8001:9001"
    environment:
      MINIO_ROOT_USER: ${MINIO_ROOT_USER}
      MINIO_ROOT_PASSWORD: ${MINIO_ROOT_PASSWORD}
    command: server --console-address ":9001" /data

volumes:
  minio-data:
    driver: local
    driver_opts:
      type: "none"
      o: "bind"
      device: "${PORTAINER_FOLDER}/minio/data"
